### ISSUE TITLE
http://localhost:9945 displays a blank page with Cannot /GET (Workaround: https://localhost:9945/qmcu/ )

### ISSUE THREAD

**Issue by paulverkooijen** [eapowertools/QlikSenseQMCUtility#68]
Hi after installing on a machine using 3.2 SR1 and a signed certificate 
I only get this message when opening the page https://localhost:9945

Cannot GET /

**Comment by xavierlp** [comment]
Hi
I've got the same issue running on windows 10.

After reading comments on issues, I tried https://localhost:9945/qmcu And I've got 
TypeError: Cannot read property 'sessionCookieHeaderName' of undefined

**Comment by paulverkooijen** [comment]
Machine is a 2008R2 server.
When I try the direct link to qmcu I get the same error.

TypeError: Cannot read property 'sessionCookieHeaderName' of undefined
    at C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\middleware\auth.js:38:50
    at Layer.handle [as handle_request] (C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\node_modules\express\lib\router\index.js:317:13)
    at C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\node_modules\express\lib\router\index.js:275:10)
    at C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\middleware\rewrite.js:36:9
    at Layer.handle [as handle_request] (C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\node_modules\express\lib\router\index.js:317:13)
    at C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\node_modules\express\lib\router\index.js:275:10)
    at C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\middleware\vpList.js:38:17
    at tryCatcher (C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\node_modules\bluebird\js\release\async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by paulverkooijen** [comment]
When I look at the used Certificate through Chrome console. It is not using the correct certificate.

**Comment by xavierlp** [comment]
it's work for me know if you enter https://servername:9945/qmcu/ 

just add / at then end of the url

HTH

**Comment by paulverkooijen** [comment]
Hey that works indeed 👍

**Comment by xavierlp** [comment]
Great 

If you can, close the issue as resolved :-)

**Comment by paulverkooijen** [comment]
Hi Xavier, wouldn't call it resolved. 
The use of this explicit URL is a workaround.

I also see another user regarding the same issue.

**Comment by goldbergjeffrey** [comment]
@paulverkooijen the use of the explicit url is a requirement.  I may add some redirection logic in the next point release that corrects not having /qmcu or /qmcu/ after the hostname and port.  Right now, affixing /qmcu/ to the path is the standard.

**Comment by paulverkooijen** [comment]
@goldbergjeffrey could you change the instructions in? https://github.com/eapowertools/QlikSenseQMCUtility/wiki/Installing-QMC-Utilities  These point to the incorrect URL
