### ISSUE TITLE
user profile / login issues?

### ISSUE THREAD

**Issue by PlexPro** [eapowertools/QlikSenseQMCUtility#71]
Not having yet logged into the Qlik Sense QMC with my standard user profile ("rvalencourt") that is defined within Qlik Sense to be a root admin, that when attempting to go to "https://localhost:9945/qmcu" in another tab (of Chrome), I got this notice:

"Your account is inactive. Contact your administrator to activate it."

It occurred to me that the process were inspecting Windows for the logged-in user (which was a different user - a Windows admin), rather than looking for a Qlik logged-in user.

If I first log in to the Qlik Sense QMC as "rvalencourt", and then attempt to go to "https://localhost:9945/qmcu" in another tab, I get this result:

TypeError: Cannot read property 'sessionCookieHeaderName' of undefined
    at C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\middleware\auth.js:38:50
    at Layer.handle [as handle_request] (C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\node_modules\express\lib\router\index.js:317:13)
    at C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\node_modules\express\lib\router\index.js:275:10)
    at C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\middleware\rewrite.js:36:9
    at Layer.handle [as handle_request] (C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\node_modules\express\lib\router\index.js:317:13)
    at C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\node_modules\express\lib\router\index.js:275:10)
    at C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\middleware\vpList.js:38:17
    at tryCatcher (C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\node_modules\bluebird\js\release\async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

Chrome is set to standard security settings with regard to cookies, to "allow local data to be set".  Any idea what I be doing wrong?

Thanks,

René V.

**Comment by paulverkooijen** [comment]
Use https://servername:9945/qmcu/ with the / at the end

**Comment by goldbergjeffrey** [comment]
@paulverkooijen said ^

**Comment by PlexPro** [comment]
This morning I tried again.

- I logged in with my Windows admin profile.

- I opened Chrome, was prompted for credentials by Qlik Sense, and provided my Qlik Sense admin info.  This is not the same as my Windows admin profile.

- I changed the URL to "https://localhost:9945/qmcu/", and got this result:  "Your account is inactive. Contact your administrator to activate it."

- I open Chrome as a different user (my Qlik Sense admin profile).  This time it works.

Hopefully this will be consistent!

Thanks,

René
