### ISSUE TITLE
"Unexpected token (" error 

### ISSUE THREAD

**Issue by johannva** [eapowertools/QlikSenseQMCUtility#85]
Using a virtual proxy and getting inconsistent results.  The QMC utilities webpage will display for a minute and as soon as I navigate to a utility I get the following error:

proxyPath Length: 9
I'm in auth.js
undefined:1
<!doctype html>
^

SyntaxError: Unexpected token <
    at Object.parse (native)
    at Request._callback (E:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilities\
middleware\auth.js:63:33)
    at Request.self.callback (E:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilit
ies\node_modules\request\request.js:187:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (E:\Program Files\Qlik\Sense\EAPowerTools\QMCUtilitie
s\node_modules\request\request.js:1126:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (E:\Program Files\Qlik\Sense\EAPowerTools\QMC
Utilities\node_modules\request\request.js:1046:12)
    at IncomingMessage.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)

**Comment by jparis** [comment]
This still an issue?
